import { db } from './client.js'
import type { InterventionOffer, InterventionStatus, AgentRole } from '../../types/index.js'

export async function createOffer(params: {
  id: string                    // pre-generated by the route, used as the waitForEvent match key
  canvas_id: string
  session_id: string
  agent_role: AgentRole
  trigger_node_id: string
  anchor_node_ids: string[]
  seq: number
  context_fingerprint: string   // canvas_version as string — change-detector, not content (§6)
}): Promise<InterventionOffer> {
  const { data, error } = await db
    .from('intervention_offers')
    .insert({
      id: params.id,
      canvas_id: params.canvas_id,
      session_id: params.session_id,
      agent_role: params.agent_role,
      trigger_node_id: params.trigger_node_id,
      anchor_node_ids: params.anchor_node_ids,
      seq: params.seq,
      context_fingerprint: params.context_fingerprint,
      status: 'waiting',
      directness: null,
      headline: null,
    })
    .select()
    .single()

  if (error) throw new Error(`createOffer failed: ${error.message}`)
  return data as InterventionOffer
}

export async function getOffer(id: string): Promise<InterventionOffer> {
  const { data, error } = await db
    .from('intervention_offers')
    .select('*')
    .eq('id', id)
    .single()

  if (error) throw new Error(`getOffer failed: ${error.message}`)
  return data as InterventionOffer
}

export async function updateOfferStatus(
  id: string,
  status: InterventionStatus,
  extra?: { directness?: string; headline?: string }
): Promise<void> {
  const update: Record<string, unknown> = { status }
  if (extra?.directness !== undefined) update.directness = extra.directness
  if (extra?.headline !== undefined) update.headline = extra.headline
  // Terminal statuses get a resolved_at timestamp.
  if (['expired', 'dismissed', 'superseded', 'pulled'].includes(status)) {
    update.resolved_at = new Date().toISOString()
  }

  const { error } = await db.from('intervention_offers').update(update).eq('id', id)
  if (error) throw new Error(`updateOfferStatus(${status}) failed: ${error.message}`)
}

export async function getActiveOffersForSession(session_id: string): Promise<InterventionOffer[]> {
  const { data, error } = await db
    .from('intervention_offers')
    .select('*')
    .eq('session_id', session_id)
    .in('status', ['waiting', 'shown'])
    .order('seq', { ascending: false })

  if (error) throw new Error(`getActiveOffersForSession failed: ${error.message}`)
  return (data ?? []) as InterventionOffer[]
}
