import { db } from './client.js'
import type { InterventionOffer, InterventionStatus, AgentRole } from '../../types/index.js'

// Atomic bump of sessions.latest_seq — a single SQL statement with RETURNING.
// Never read-modify-write in application code: concurrent Inngest workers
// racing on the same session would otherwise both hand back the same seq.
export async function allocateSeq(session_id: string): Promise<number> {
  const { data, error } = await db.rpc('allocate_session_seq', { p_session_id: session_id })
  if (error) throw new Error(`allocateSeq failed: ${error.message}`)
  return data as number
}

// Reads the monotonic latest_seq for the session. Used by the version guard
// (isStillLatest in src/lib/guards.ts) to abort a stale run at the publish
// boundary — see DESIGN §4e.
export async function getLatestSeq(session_id: string): Promise<number> {
  const { data, error } = await db
    .from('sessions')
    .select('latest_seq')
    .eq('id', session_id)
    .single()
  if (error) throw new Error(`getLatestSeq failed: ${error.message}`)
  return (data as { latest_seq: number }).latest_seq
}

// Supersede a parked offer: mark it superseded (terminal) + set resolved_at.
// The pipeline then publishes 'withdraw' + fires the cancel event; the parked
// Inngest run cancels via cancelOn, and any stale run wakes to a lost version
// guard and aborts silently.
export async function markSuperseded(id: string): Promise<void> {
  const { error } = await db
    .from('intervention_offers')
    .update({ status: 'superseded', resolved_at: new Date().toISOString() })
    .eq('id', id)
  if (error) throw new Error(`markSuperseded failed: ${error.message}`)
}

// Any waiting or shown offer for this session. Read at the top of a new
// pipeline to trigger supersession — single-flight per session (§4e).
export async function getInFlightForSession(session_id: string): Promise<InterventionOffer[]> {
  const { data, error } = await db
    .from('intervention_offers')
    .select('*')
    .eq('session_id', session_id)
    .in('status', ['waiting', 'shown'])
  if (error) throw new Error(`getInFlightForSession failed: ${error.message}`)
  return (data ?? []) as InterventionOffer[]
}

// Any waiting or shown offer anchored to this trigger node. canAgentFire uses
// this to block a duplicate pipeline on the same node before an offer has
// reached the ghost-pair stage the thread-based check would catch.
export async function hasInFlightForTriggerNode(
  canvas_id: string,
  trigger_node_id: string
): Promise<boolean> {
  const { count, error } = await db
    .from('intervention_offers')
    .select('id', { count: 'exact', head: true })
    .eq('canvas_id', canvas_id)
    .eq('trigger_node_id', trigger_node_id)
    .in('status', ['waiting', 'shown'])
  if (error) throw new Error(`hasInFlightForTriggerNode failed: ${error.message}`)
  return (count ?? 0) > 0
}

export async function createOffer(params: {
  id: string                    // pre-generated by the route, used as the waitForEvent match key
  canvas_id: string
  session_id: string
  agent_role: AgentRole
  trigger_node_id: string
  anchor_node_ids: string[]
  seq: number
  context_fingerprint: string   // canvas_version as string — change-detector, not content (§6)
}): Promise<InterventionOffer> {
  const { data, error } = await db
    .from('intervention_offers')
    .insert({
      id: params.id,
      canvas_id: params.canvas_id,
      session_id: params.session_id,
      agent_role: params.agent_role,
      trigger_node_id: params.trigger_node_id,
      anchor_node_ids: params.anchor_node_ids,
      seq: params.seq,
      context_fingerprint: params.context_fingerprint,
      status: 'waiting',
      directness: null,
      headline: null,
    })
    .select()
    .single()

  if (error) throw new Error(`createOffer failed: ${error.message}`)
  return data as InterventionOffer
}

export async function getOffer(id: string): Promise<InterventionOffer> {
  const { data, error } = await db
    .from('intervention_offers')
    .select('*')
    .eq('id', id)
    .single()

  if (error) throw new Error(`getOffer failed: ${error.message}`)
  return data as InterventionOffer
}

export async function updateOfferStatus(
  id: string,
  status: InterventionStatus,
  extra?: { directness?: string; headline?: string }
): Promise<void> {
  const update: Record<string, unknown> = { status }
  if (extra?.directness !== undefined) update.directness = extra.directness
  if (extra?.headline !== undefined) update.headline = extra.headline
  // Terminal statuses get a resolved_at timestamp.
  if (['expired', 'dismissed', 'superseded', 'pulled'].includes(status)) {
    update.resolved_at = new Date().toISOString()
  }

  const { error } = await db.from('intervention_offers').update(update).eq('id', id)
  if (error) throw new Error(`updateOfferStatus(${status}) failed: ${error.message}`)
}

export async function getActiveOffersForSession(session_id: string): Promise<InterventionOffer[]> {
  const { data, error } = await db
    .from('intervention_offers')
    .select('*')
    .eq('session_id', session_id)
    .in('status', ['waiting', 'shown'])
    .order('seq', { ascending: false })

  if (error) throw new Error(`getActiveOffersForSession failed: ${error.message}`)
  return (data ?? []) as InterventionOffer[]
}
